// lib/theme/material_theme.dart
//
// Salmon Material 3 theme — generated by Google Material Theme Builder.
// Seed colour: Salmon.
//
// To swap themes, replace this file with another Material Theme Builder
// export (keeping the class name MaterialTheme).
//
// Usage in main.dart:
//   final textTheme = createTextTheme(context, 'Roboto', 'Noto Sans');
//   final theme = MaterialTheme(textTheme);
//   MaterialApp(darkTheme: theme.dark(), themeMode: ThemeMode.dark, ...)

import "package:flutter/material.dart";

class MaterialTheme {
  final TextTheme textTheme;

  const MaterialTheme(this.textTheme);

  static ColorScheme lightScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff8e4d31),
      surfaceTint: Color(0xff8e4d31),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffffdbce),
      onPrimaryContainer: Color(0xff71361c),
      secondary: Color(0xff77574b),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffffdbce),
      onSecondaryContainer: Color(0xff5d4035),
      tertiary: Color(0xff685f30),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xfff1e3a8),
      onTertiaryContainer: Color(0xff4f471a),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      surface: Color(0xfffff8f6),
      onSurface: Color(0xff231a16),
      onSurfaceVariant: Color(0xff53433e),
      outline: Color(0xff85736d),
      outlineVariant: Color(0xffd8c2bb),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff392e2a),
      inversePrimary: Color(0xffffb599),
      primaryFixed: Color(0xffffdbce),
      onPrimaryFixed: Color(0xff370e00),
      primaryFixedDim: Color(0xffffb599),
      onPrimaryFixedVariant: Color(0xff71361c),
      secondaryFixed: Color(0xffffdbce),
      onSecondaryFixed: Color(0xff2c160d),
      secondaryFixedDim: Color(0xffe7beaf),
      onSecondaryFixedVariant: Color(0xff5d4035),
      tertiaryFixed: Color(0xfff1e3a8),
      onTertiaryFixed: Color(0xff211b00),
      tertiaryFixedDim: Color(0xffd4c78e),
      onTertiaryFixedVariant: Color(0xff4f471a),
      surfaceDim: Color(0xffe8d6d1),
      surfaceBright: Color(0xfffff8f6),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff1ec),
      surfaceContainer: Color(0xfffceae4),
      surfaceContainerHigh: Color(0xfff6e4de),
      surfaceContainerHighest: Color(0xfff1dfd9),
    );
  }

  ThemeData light() {
    return theme(lightScheme());
  }

  static ColorScheme lightMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff5c260e),
      surfaceTint: Color(0xff8e4d31),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffa05b3e),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff4a3025),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff876659),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff3e360b),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff776d3d),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff740006),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffcf2c27),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffff8f6),
      onSurface: Color(0xff170f0c),
      onSurfaceVariant: Color(0xff41332e),
      outline: Color(0xff5f4f49),
      outlineVariant: Color(0xff7b6963),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff392e2a),
      inversePrimary: Color(0xffffb599),
      primaryFixed: Color(0xffa05b3e),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff834329),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff876659),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff6c4e42),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff776d3d),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff5e5527),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffd4c3bd),
      surfaceBright: Color(0xfffff8f6),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfffff1ec),
      surfaceContainer: Color(0xfff6e4de),
      surfaceContainerHigh: Color(0xffebd9d3),
      surfaceContainerHighest: Color(0xffdfcec8),
    );
  }

  ThemeData lightMediumContrast() {
    return theme(lightMediumContrastScheme());
  }

  static ColorScheme lightHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.light,
      primary: Color(0xff4f1c05),
      surfaceTint: Color(0xff8e4d31),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xff74381f),
      onPrimaryContainer: Color(0xffffffff),
      secondary: Color(0xff3f261c),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xff5f4237),
      onSecondaryContainer: Color(0xffffffff),
      tertiary: Color(0xff332c03),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xff52491d),
      onTertiaryContainer: Color(0xffffffff),
      error: Color(0xff600004),
      onError: Color(0xffffffff),
      errorContainer: Color(0xff98000a),
      onErrorContainer: Color(0xffffffff),
      surface: Color(0xfffff8f6),
      onSurface: Color(0xff000000),
      onSurfaceVariant: Color(0xff000000),
      outline: Color(0xff362924),
      outlineVariant: Color(0xff554640),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff392e2a),
      inversePrimary: Color(0xffffb599),
      primaryFixed: Color(0xff74381f),
      onPrimaryFixed: Color(0xffffffff),
      primaryFixedDim: Color(0xff58220a),
      onPrimaryFixedVariant: Color(0xffffffff),
      secondaryFixed: Color(0xff5f4237),
      onSecondaryFixed: Color(0xffffffff),
      secondaryFixedDim: Color(0xff462c22),
      onSecondaryFixedVariant: Color(0xffffffff),
      tertiaryFixed: Color(0xff52491d),
      onTertiaryFixed: Color(0xffffffff),
      tertiaryFixedDim: Color(0xff3a3308),
      onTertiaryFixedVariant: Color(0xffffffff),
      surfaceDim: Color(0xffc6b5b0),
      surfaceBright: Color(0xfffff8f6),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xffffede7),
      surfaceContainer: Color(0xfff1dfd9),
      surfaceContainerHigh: Color(0xffe2d1cb),
      surfaceContainerHighest: Color(0xffd4c3bd),
    );
  }

  ThemeData lightHighContrast() {
    return theme(lightHighContrastScheme());
  }

  static ColorScheme darkScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffb599),
      surfaceTint: Color(0xffffb599),
      onPrimary: Color(0xff552008),
      primaryContainer: Color(0xff71361c),
      onPrimaryContainer: Color(0xffffdbce),
      secondary: Color(0xffe7beaf),
      onSecondary: Color(0xff442a20),
      secondaryContainer: Color(0xff5d4035),
      onSecondaryContainer: Color(0xffffdbce),
      tertiary: Color(0xffd4c78e),
      onTertiary: Color(0xff383006),
      tertiaryContainer: Color(0xff4f471a),
      onTertiaryContainer: Color(0xfff1e3a8),
      error: Color(0xffffb4ab),
      onError: Color(0xff690005),
      errorContainer: Color(0xff93000a),
      onErrorContainer: Color(0xffffdad6),
      surface: Color(0xff1a110e),
      onSurface: Color(0xfff1dfd9),
      onSurfaceVariant: Color(0xffd8c2bb),
      outline: Color(0xffa08d86),
      outlineVariant: Color(0xff53433e),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xfff1dfd9),
      inversePrimary: Color(0xff8e4d31),
      primaryFixed: Color(0xffffdbce),
      onPrimaryFixed: Color(0xff370e00),
      primaryFixedDim: Color(0xffffb599),
      onPrimaryFixedVariant: Color(0xff71361c),
      secondaryFixed: Color(0xffffdbce),
      onSecondaryFixed: Color(0xff2c160d),
      secondaryFixedDim: Color(0xffe7beaf),
      onSecondaryFixedVariant: Color(0xff5d4035),
      tertiaryFixed: Color(0xfff1e3a8),
      onTertiaryFixed: Color(0xff211b00),
      tertiaryFixedDim: Color(0xffd4c78e),
      onTertiaryFixedVariant: Color(0xff4f471a),
      surfaceDim: Color(0xff1a110e),
      surfaceBright: Color(0xff423733),
      surfaceContainerLowest: Color(0xff140c09),
      surfaceContainerLow: Color(0xff231a16),
      surfaceContainer: Color(0xff271e1a),
      surfaceContainerHigh: Color(0xff322824),
      surfaceContainerHighest: Color(0xff3d322f),
    );
  }

  ThemeData dark() {
    return theme(darkScheme());
  }

  static ColorScheme darkMediumContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffd3c3),
      surfaceTint: Color(0xffffb599),
      onPrimary: Color(0xff471601),
      primaryContainer: Color(0xffca7d5e),
      onPrimaryContainer: Color(0xff000000),
      secondary: Color(0xfffed3c4),
      onSecondary: Color(0xff382016),
      secondaryContainer: Color(0xffad897b),
      onSecondaryContainer: Color(0xff000000),
      tertiary: Color(0xffeadda2),
      onTertiary: Color(0xff2c2500),
      tertiaryContainer: Color(0xff9c915d),
      onTertiaryContainer: Color(0xff000000),
      error: Color(0xffffd2cc),
      onError: Color(0xff540003),
      errorContainer: Color(0xffff5449),
      onErrorContainer: Color(0xff000000),
      surface: Color(0xff1a110e),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffeed8d0),
      outline: Color(0xffc2aea6),
      outlineVariant: Color(0xff9f8c86),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xfff1dfd9),
      inversePrimary: Color(0xff73371d),
      primaryFixed: Color(0xffffdbce),
      onPrimaryFixed: Color(0xff260700),
      primaryFixedDim: Color(0xffffb599),
      onPrimaryFixedVariant: Color(0xff5c260e),
      secondaryFixed: Color(0xffffdbce),
      onSecondaryFixed: Color(0xff200c04),
      secondaryFixedDim: Color(0xffe7beaf),
      onSecondaryFixedVariant: Color(0xff4a3025),
      tertiaryFixed: Color(0xfff1e3a8),
      onTertiaryFixed: Color(0xff151100),
      tertiaryFixedDim: Color(0xffd4c78e),
      onTertiaryFixedVariant: Color(0xff3e360b),
      surfaceDim: Color(0xff1a110e),
      surfaceBright: Color(0xff4d423e),
      surfaceContainerLowest: Color(0xff0d0604),
      surfaceContainerLow: Color(0xff251c18),
      surfaceContainer: Color(0xff302622),
      surfaceContainerHigh: Color(0xff3b302c),
      surfaceContainerHighest: Color(0xff463b37),
    );
  }

  ThemeData darkMediumContrast() {
    return theme(darkMediumContrastScheme());
  }

  static ColorScheme darkHighContrastScheme() {
    return const ColorScheme(
      brightness: Brightness.dark,
      primary: Color(0xffffece6),
      surfaceTint: Color(0xffffb599),
      onPrimary: Color(0xff000000),
      primaryContainer: Color(0xffffb091),
      onPrimaryContainer: Color(0xff1c0400),
      secondary: Color(0xffffece6),
      onSecondary: Color(0xff000000),
      secondaryContainer: Color(0xffe3baab),
      onSecondaryContainer: Color(0xff180602),
      tertiary: Color(0xfffff0b4),
      onTertiary: Color(0xff000000),
      tertiaryContainer: Color(0xffd0c38b),
      onTertiaryContainer: Color(0xff0e0b00),
      error: Color(0xffffece9),
      onError: Color(0xff000000),
      errorContainer: Color(0xffffaea4),
      onErrorContainer: Color(0xff220001),
      surface: Color(0xff1a110e),
      onSurface: Color(0xffffffff),
      onSurfaceVariant: Color(0xffffffff),
      outline: Color(0xffffece6),
      outlineVariant: Color(0xffd4beb7),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xfff1dfd9),
      inversePrimary: Color(0xff73371d),
      primaryFixed: Color(0xffffdbce),
      onPrimaryFixed: Color(0xff000000),
      primaryFixedDim: Color(0xffffb599),
      onPrimaryFixedVariant: Color(0xff260700),
      secondaryFixed: Color(0xffffdbce),
      onSecondaryFixed: Color(0xff000000),
      secondaryFixedDim: Color(0xffe7beaf),
      onSecondaryFixedVariant: Color(0xff200c04),
      tertiaryFixed: Color(0xfff1e3a8),
      onTertiaryFixed: Color(0xff000000),
      tertiaryFixedDim: Color(0xffd4c78e),
      onTertiaryFixedVariant: Color(0xff151100),
      surfaceDim: Color(0xff1a110e),
      surfaceBright: Color(0xff5a4d49),
      surfaceContainerLowest: Color(0xff000000),
      surfaceContainerLow: Color(0xff271e1a),
      surfaceContainer: Color(0xff392e2a),
      surfaceContainerHigh: Color(0xff443935),
      surfaceContainerHighest: Color(0xff504440),
    );
  }

  ThemeData darkHighContrast() {
    return theme(darkHighContrastScheme());
  }

  ThemeData theme(ColorScheme colorScheme) => ThemeData(
    useMaterial3: true,
    brightness: colorScheme.brightness,
    colorScheme: colorScheme,
    textTheme: textTheme.apply(
      bodyColor: colorScheme.onSurface,
      displayColor: colorScheme.onSurface,
    ),
    scaffoldBackgroundColor: colorScheme.surface,
    canvasColor: colorScheme.surface,
  );

  List<ExtendedColor> get extendedColors => [];
}

class ExtendedColor {
  final Color seed, value;
  final ColorFamily light;
  final ColorFamily lightHighContrast;
  final ColorFamily lightMediumContrast;
  final ColorFamily dark;
  final ColorFamily darkHighContrast;
  final ColorFamily darkMediumContrast;

  const ExtendedColor({
    required this.seed,
    required this.value,
    required this.light,
    required this.lightHighContrast,
    required this.lightMediumContrast,
    required this.dark,
    required this.darkHighContrast,
    required this.darkMediumContrast,
  });
}

class ColorFamily {
  const ColorFamily({
    required this.color,
    required this.onColor,
    required this.colorContainer,
    required this.onColorContainer,
  });

  final Color color;
  final Color onColor;
  final Color colorContainer;
  final Color onColorContainer;
}
